port: 8899

db:
  type: mysql
  host: 127.0.0.1:3306
  hostR1: 127.0.0.1:3306
  user: root
  password: 123456
  name: step2money

redis:
  addr: 127.0.0.1:6379

weApp:
  appId:
  secret:

qiniu:
  accessKey:
  secretKey:
